### ISSUE TITLE
Morganey Hangs when running from inside intellij

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#214]

**Comment by rexim** [comment]
@06needhamt please provide detailed instruction on how to reproduce that.

**Comment by 06needhamt** [comment]
Sorry Forgot to add them created this in a rush
Steps To Reproduce
1. Follow The Instructions in https://github.com/morganey-lang/morganey-intellij-plugin/blob/master/CONTRIBUTING.md To Build and Launch The Plugin
2. Open The 'test' Project Located Inside The Plugin Repo In The Launched Instance Of IntelliJ
3. Launch The 'test' Project By Clicking The Run Button
4. A Morganey Console Should Open At The Bottom Of The Editor
5. Try To Run Some Morganey Commands
6. Morganey 'Hangs' Indefinitely i.e. Never Completes The Requested Computation
7. Stop The Test Project

Hope This Helps You Solve The Issue

**Comment by rexim** [comment]
@06needhamt Great! Thank you very much! I'm gonna look into that tomorrow after my work. 

Also, any of the Morganey core contributers feel free to help with this incident if you want and have time. Thanks!

**Comment by 06needhamt** [comment]
@rexim Forgot to mention also make sure you are using the fat-jar branch

**Comment by rexim** [comment]
Alright, looking into this one.

**Comment by rexim** [comment]
@06needhamt your problem is caused by this bug #215. I'm gonna fix it on Sunday's stream. In the mean time I suggest to take a look at the workaround section of the bug description.

**Comment by rexim** [comment]
@06needhamt, the workaround is basically to send EOF to the stdin of the Morganey. 

I don't know if `Ctrl+D` on Windows send EOF to stdin, but it worth trying:
- Launch the `test` project in the intellij instance
- Focus to the console
- Press `Ctrl+D`

cc @ForNeVeR

**Comment by rexim** [comment]
@06needhamt another thing, unfortunetely the fatjar doesn't contain the standard library of Morganey. So even if you run your sample successfully it will complain about non-existing prelude module. You can find the standard library at [std/](https://github.com/morganey-lang/Morganey/tree/7c04f6678f4ddc39e04753b694371ac3f6e76275/std) folder of Morganery repo. Morganey interpreter searches for `std/` in its working directory. So please copy it there.

**Comment by 06needhamt** [comment]
@rexim I Tried Your Suggestion But It Still Hangs

**Comment by rexim** [comment]
@06needhamt alright, maybe on Windows it's done somehow differently... Let wait for the fix of #215 then.

Btw, have you tried to run the sample outside of Intellij in a console? Does it hang there for you too?

**Comment by 06needhamt** [comment]
Nope it runs properly in the console outside of IntelliJ

**Comment by rexim** [comment]
@06needhamt could you please show me how you run it in the console?

**Comment by 06needhamt** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4162227/18794827/51119fee-81b9-11e6-9a49-0a35ca911a5e.png)

**Comment by 06needhamt** [comment]
Did a bit of debugging tonight and it is in fact the Intellij Console which hangs not Morganey.

The Idea Console hangs with the following error `"read Windows console input error: "` So it looks like this is in fact an IntelliJ issue not a Morganey Issue

**Comment by 06needhamt** [comment]
Reported Issue To Jetbrains [here](https://youtrack.jetbrains.com/issue/IDEA-161678)

**Comment by rexim** [comment]
@06needhamt ah, alright! Thanks! 

But #215 is still present and I'm gonna fix it tomorrow.

**Comment by rexim** [comment]
@06needhamt #215 is fixed. Please try the latest version of Morganey from the master.

**Comment by 06needhamt** [comment]
@rexim It Still hangs as before however someone is working on the [issue](https://youtrack.jetbrains.com/issue/IDEA-161678) at JetBeains now hopefully it will be fixed soon

**Comment by rexim** [comment]
It maybe even Windows specific problem. For me on linux everything works well with the following environment
- NixOS 16.03
- Intellij IDEA Community 2016.2
- Morganey commit 98612d456b19bbb2d1a380cc699b1bc64e2ddd6b
- Morganey Intellij Plugin commit 74528a0f8ece3955a576fde65e95822bdce0a618

![screenshot from 2016-09-26 22-08-42](https://cloud.githubusercontent.com/assets/165283/18842176/65cb8558-843e-11e6-9768-333c0ec722c7.png)

**Comment by 06needhamt** [comment]
@rexim I can confirm that it is a windows specific problem or a problem with Intellij IDEA Community 2016.3. Can you please post a screenshot of the dialog from the Morganey | About This Plugin  menu

**Comment by rexim** [comment]
![screenshot from 2016-09-26 22-28-43](https://cloud.githubusercontent.com/assets/165283/18842953/0a30faea-8441-11e6-8735-bc656adc54fa.png)

**Comment by ForNeVeR** [comment]
@06needhamt, @rexim I think I've solved the riddle. That wasn't Windows or IDEA fault, that was the Morganey artifact in `morganey-intellij-plugin` repository.

The main clue is that the artifact [`morganey_2.11-0.0.1-SNAPSHOT.jar`](https://github.com/morganey-lang/morganey-intellij-plugin/blob/768bda523691534bfa721e9904cd25a2acfbea36/lib/morganey_2.11-0.0.1-SNAPSHOT.jar) is unable to execute your `test.morg` at all. Just try that from a command line — and it will hang just as IDEA. So, it's just a bug of that artifact, and not a general Windows / IDEA issue.

And here's how to solve the problem:
1. Build Morganey using `sbt assembly`.
2. Clone `morganey-intellij-plugin`.
3. **Replace** `morganey-intellij-plugin\lib\morganey_2.11-0.0.1-SNAPSHOT.jar` with `Morganey\target\scala-2.11\morganey-assembly-0.0.1-SNAPSHOT.jar`.
4. Try to execute the Morganey from IDEA as written in [`CONTRIBUTING.md`](https://github.com/morganey-lang/morganey-intellij-plugin/blob/768bda523691534bfa721e9904cd25a2acfbea36/CONTRIBUTING.md).
5. Observe the proper behavior!

Here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/92793/18845941/ee13e5fe-844d-11e6-9d39-5f23892580cf.png)

So, the problem is that you're using some buggy version of Morganey currently in your repository. Please replace it for now with the latest version of the "uberjar".

We'll set up the standard dependency system in scope of #210, so you'll be able to add Morganey as a project dependency from jcenter instead of relying on a binary in the repository.

If this helped you, please don't forget to close the corresponding IDEA bug. There's no need to distract JetBrains guys — after all, we've found that it's our issue and not theirs.

**Comment by 06needhamt** [comment]
👍 Thanks @ForNeVeR Will Try that now

**Comment by 06needhamt** [comment]
@ForNeVeR This fixes the issue when reading from a source file but the issue still occurrs when typing commands directly into the repl

**Comment by ForNeVeR** [comment]
Oh, sorry, I haven't checked this case. Will take a look ASAP!

**Comment by 06needhamt** [comment]
@ForNeVeR Did you get a chance to take a look at this?

**Comment by ForNeVeR** [comment]
Sorry, wasn't a possibility for me these days. Will try to take a look at the weekend, i.e. tomorrow.

**Comment by 06needhamt** [comment]
@ForNeVeR Ok no problem

**Comment by ForNeVeR** [comment]
Yep, I was able to reproduce the issue.

And it may actually be a Morganey bug. When being executed through IDEA, it constantly eats my CPU. Probably something's weird if the process output got redirected in Windows environment, I wouldn't be surprised. Will investigate further.

**Comment by ForNeVeR** [comment]
And it may actually be a Morganey bug. When being executed through IDEA, it constantly eats my CPU. Probably something's weird if the process output got redirected in Windows environment, I wouldn't be surprised. Will investigate further.

**Comment by ForNeVeR** [comment]
Was able to reproduce with `cmd.exe` (as the lowest replacement for a Windows shell). Call this inside of a Morganey repository:

``` console
$ sbt assembly
$ echo :exit | java -Dfile.encoding=windows-1251 -jar target\scala-2.11\morganey.jar
?>
```

I think that it should exit immediately after the start, but it just keeping showing me a `?>` prompt and not accepting any input at all. Something strange definitely's happening in Morganey itself.

**Comment by rexim** [comment]
@ForNeVeR lemme quickly try that on Linups

**Comment by rexim** [comment]
```
$ echo :exit | java -jar target/scala-2.11/morganey.jar 
λ> :exit
$
```

Exited clearly on my machine.

**Comment by rexim** [comment]
Can be something with JLine.

**Comment by rexim** [comment]
@ForNeVeR can we split that into a separate bug?

**Comment by rexim** [comment]
@06needhamt #234 has been fixed. Please try the latest version of Morganey.
